### ISSUE TITLE
El programa permite crear Homomorfismos que no lo son.

### ISSUE THREAD

**Issue by gonzigaran** [pablogventura/definability#72]
Por ejemplo:
h = definability.morphisms.Homomorphism({(0,):1,(1,):0,(3,):2,(2,):3}, A, A, A.fo_type)

con A el rombo

**Comment by pablogventura** [comment]
Si, lo que pasa es que esa clase esta pensada para ser usada solo como resultado de llamar a Minion. Por ejemplo usando A.homomorphisms_to(A, A.fo_type)
